export default {
    SET_SINGER: "SET_SINGER",

    SET_PLAYING: "SET_PLAYING",
    SET_FULLSCRENN: "SET_FULLSCRENN",
    SET_PLAYMODE: "SET_PLAYMODE",
    SET_PLAYLIST: "SET_PLAYLIST",
    SET_SEQUENCELIST: "SET_SEQUENCELIST",
    SET_CURRENTINDEX: "SET_CURRENTINDEX",

    SET_DISC: "SET_DISC"
}